version: "3"

services:
  mag_php:
    build: ./docker/php
    ports:
      - 8083:80
    volumes:
      - "./src:/var/www/html"
      - "./docker/php/downloads:/var/www/html/downloads"
      - "./docker/conf/db.ini:/var/www/html/db.ini:rw"
    depends_on:
      - mag_mariadb
    networks:
    - titleSite

  mag_mariadb:
      image: mariadb:10.9
      ports:
        - 3310:3306
      volumes:
        - ./docker/mariadb/database:/var/lib/mysql
        - ./docker/mariadb/dump:/var/backups:rw
      env_file:
        - ./docker/conf/db.ini
      networks:
      - titleSite

networks:
  titleSite:
    external: true
    name: titleSite
    driver: bridge