version: "3"

services:
  mag_php:
    build: ./docker/php
    ports:
      - 8085:80
    volumes:
      - "./src:/var/www/html"
      - "./docker/php/downloads:/var/www/html/downloads"
    # command: chown -R www-data:www-data /var/www/html/downloads
    depends_on:
      - mag_mariadb

  mag_mariadb:
      image: mariadb:10.9
      ports:
        - 3310:3306
      volumes:
        - ./docker/mariadb/database:/var/lib/mysql
        - ./docker/mariadb/dump:/home
      environment:
        # - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_DATABASE=mydatabase
        # - MARIADB_PORT_NUMBER=3306
        # - MARIADB_ROOT_USER=root
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_USER=myuser
        - MARIADB_PASSWORD=mypassword
