version: "3"

services:
  sapper_php:
    image: php:8.1.18-fpm
    volumes:
      - "./src:/var/www/html"
      - "./docker/volumes/composer:/var/www/"

  sapper_nginx:
    image: nginx:latest
    ports:
      - 8081:80
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
